-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.materials
(
    id integer NOT NULL,
    defect_percentage numeric(10, 5),
    CONSTRAINT materials_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.partner_products
(
    id integer NOT NULL,
    product_name text COLLATE pg_catalog."default",
    partner_id integer,
    amount integer,
    sell_date date,
    CONSTRAINT partner_products_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.partners
(
    id integer NOT NULL,
    type character varying(3) COLLATE pg_catalog."default",
    name text COLLATE pg_catalog."default",
    ceo_name text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    phone text COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    itn text COLLATE pg_catalog."default",
    rating integer,
    CONSTRAINT partners_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id integer NOT NULL,
    type text COLLATE pg_catalog."default",
    name text COLLATE pg_catalog."default",
    article text COLLATE pg_catalog."default",
    min_price numeric(10, 2),
    coefficient numeric(3, 2),
    defect_percentage numeric,
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT products_article_key UNIQUE (article)
);

ALTER TABLE IF EXISTS public.partner_products
    ADD CONSTRAINT partner_products_partner_id_fkey FOREIGN KEY (partner_id)
    REFERENCES public.partners (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;